// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class AquaSupplies
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public decimal SalePrice { get; set; }

    public double Size { get; set; }

    public string Description { get; set; }

    public bool Taxable { get; set; }

    public int Stock { get; set; }

    public int SupplierId { get; set; }

    public DateOnly SaleStartDate { get; set; }

    public DateOnly SaleEndDate { get; set; }

    public int MearsurementId { get; set; }

    public virtual Measurement Mearsurement { get; set; }

    public virtual Supplier Supplier { get; set; }

 }