// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class CustomerPhoneNumber
{
    public int CustomerId { get; set; }

    public int PhoneNumberId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual PhoneNumber PhoneNumber { get; set; }
}