// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class CustomersAddress
{
    public int CustomerId { get; set; }

    public int AddressId { get; set; }

    public virtual Address Address { get; set; }

    public virtual Customer Customer { get; set; }
}