// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class FishesFood
{
    public int FishId { get; set; }

    public int FoodId { get; set; }

    public virtual Fish Fish { get; set; }

    public virtual Food Food { get; set; }
}