// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class Fish
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Species { get; set; }

    public string Size { get; set; }

    public int MeasurementId { get; set; }

    public string Color { get; set; }

    public double Price { get; set; }

    public int Stock { get; set; }

    public bool IsSpecialOrder { get; set; }

    public string Description { get; set; }

    public byte[] Image { get; set; }

    public int CountryId { get; set; }

    public int SupplierId { get; set; }

    public int WaterTypeId { get; set; }

    public int AggressionLevelId { get; set; }

    public virtual AggressionLevel AggressionLevel { get; set; }

    public virtual Country Country { get; set; }

    public virtual Measurement Measurement { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual WaterType WaterType { get; set; }
}