// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class Food
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double Price { get; set; }

    public double SalePrice { get; set; }

    public double Size { get; set; }

    public double Taxable { get; set; }

    public int Stock { get; set; }

    public DateOnly SaleStartDate { get; set; }

    public DateOnly SaleEndDate { get; set; }

    public int FoodTypeId { get; set; }

    public int MearsurementId { get; set; }

    public virtual FoodType FoodType { get; set; }

    public virtual Measurement Mearsurement { get; set; }
}