// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class OrdersPlant
{
    public int OrderId { get; set; }

    public int PlantId { get; set; }

    public virtual Plant Plant { get; set; }

    public virtual Order Order { get; set; }
}