// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class OrdersFish
{
    public int OrderId { get; set; }

    public int FishId { get; set; }

    public virtual Fish Fish { get; set; }

    public virtual Order Order { get; set; }
}