// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class Order
{
    public int Id { get; set; }

    public DateOnly OrderDate { get; set; }

    public decimal Total { get; set; }

    public int AddressId { get; set; }

    public int CustomerId { get; set; }

    public int OrderStatusId { get; set; }

    public virtual Address Address { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual OrderStatus OrderStatus { get; set; }
}