// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FintasticFish.Data.Entities;

public partial class Supplier
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ContactName { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public int SupplierTypeId { get; set; }

    public string Notes { get; set; }

    public int CountryId { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<Fish> Fish { get; set; } = new List<Fish>();

    public virtual SupplierType SupplierType { get; set; }
}